# Generated by Django 3.2.6 on 2021-08-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sectors',
            new_name='Sector',
        ),
    ]
