# Generated by Django 3.2.6 on 2021-08-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0003_alter_sector_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('instrument_type', models.CharField(max_length=20)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='stock_api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='StockUpdateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LivePirce',
            fields=[
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock_api.company')),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('previous_close', models.FloatField()),
                ('last_traded_price', models.FloatField()),
                ('total_volume', models.IntegerField()),
                ('percentage_change', models.FloatField()),
                ('last_updated_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('previous_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('percentage_change', models.FloatField()),
                ('total_volume', models.IntegerField()),
                ('date', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_api.company')),
            ],
        ),
    ]
