# Generated by Django 3.2.6 on 2021-08-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0004_company_livepirce_stockprice_stockupdatetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='instrument_type',
            field=models.CharField(max_length=100),
        ),
    ]
