# Generated by Django 3.2.6 on 2021-08-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0007_rename_company_id_stockprice_company'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockprice',
            constraint=models.UniqueConstraint(fields=('company', 'date'), name='stock traded day'),
        ),
    ]
