# Generated by Django 3.2.6 on 2021-08-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0008_stockprice_stock traded day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprice',
            old_name='previous_price',
            new_name='previous_close_price',
        ),
    ]
