# Generated by Django 3.2.6 on 2021-08-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0009_rename_previous_price_stockprice_previous_close_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepirce',
            name='last_traded_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
