# Generated by Django 3.2.6 on 2021-08-17 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_api', '0010_livepirce_last_traded_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='stock_api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(blank=True, default=None, null=True)),
                ('transaction_type', models.CharField(choices=[('IPO', 'IPO'), ('FPO', 'FPO'), ('right', 'Right'), ('auction', 'Auction'), ('bonus', 'Bonus'), ('dividend', 'Dividend'), ('secondary buy', 'Secondary buy'), ('sell', 'Secondary sell')], max_length=20)),
                ('price_per_unit', models.FloatField(blank=True, default=None, null=True)),
                ('transaction_date', models.DateField()),
                ('sebon_charge', models.FloatField(blank=True, default=None, null=True)),
                ('broker_charge', models.FloatField(blank=True, default=None, null=True)),
                ('dp_charge', models.FloatField(blank=True, default=None, null=True)),
                ('auction_charge', models.FloatField(blank=True, default=None, null=True)),
                ('casba_charge', models.FloatField(blank=True, default=None, null=True)),
                ('capital_gain_tax', models.FloatField(blank=True, default=None, null=True)),
                ('bonus_amount', models.FloatField(blank=True, default=None, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'stock_transaction',
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='stock user company'),
        ),
    ]
