# Generated by Django 3.2.6 on 2021-08-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price_per_unit',
            new_name='cost_per_unit',
        ),
    ]
