# Generated by Django 3.2.6 on 2021-08-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_price_per_unit_transaction_cost_per_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['company__name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['transaction_date']},
        ),
    ]
