# Generated by Django 3.2.6 on 2021-08-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alert_targetstoploss_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notify_max_to_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='notify_min_to_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='notify_to_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetstoploss',
            name='notify_stop_loss_to_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetstoploss',
            name='notify_target_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
