# Generated by Django 3.2.6 on 2021-08-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210824_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='note',
            new_name='notes',
        ),
    ]
