# Generated by Django 3.2.6 on 2021-08-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_note_alert_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='note',
            new_name='notes',
        ),
    ]
