# Generated by Django 3.2.6 on 2021-08-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_note_watchlist_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='notify_max_to_user',
            new_name='notify',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='notify_min_to_user',
            new_name='notify_max',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='notify_to_user',
            new_name='notify_min',
        ),
        migrations.RenameField(
            model_name='targetstoploss',
            old_name='notify_stop_loss_to_user',
            new_name='notify_stop_loss',
        ),
        migrations.RenameField(
            model_name='targetstoploss',
            old_name='notify_target_to_user',
            new_name='notify_target',
        ),
        migrations.AddField(
            model_name='alert',
            name='enable_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='targetstoploss',
            name='enable_notification',
            field=models.BooleanField(default=True),
        ),
    ]
